name: Advanced Custom Fields Updater

# Run this workflow twice daily
on:
  # schedule:
  #   - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  PACKAGE_SLUG: advanced-custom-fields-pro

jobs:
  update-plugin:
    name: Fetch and check versions
    runs-on: ubuntu-latest

    steps:

      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Fetch latest version
      - name: Fetch
        run: wget 'https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k=${{secrets.ACF_PRO_LICENSE}}' -O package.zip

      # Get the latest plugin and compare versions, commit if necessary
      - uses: ./.github/actions/update-plugin
        name: Update WordPress Plugin
        with:
          package-slug: ${{ env.PACKAGE_SLUG }}
          package-file-name: package.zip
