name: FacetWP Updater

# Run this workflow twice daily
on:
  # schedule:
  #   - cron: '0 */12 * * *'
  workflow_dispatch:

env:
<<<<<<< Updated upstream:.github/workflows/examples/edd.yml
  # The plugin slug
  PACKAGE_SLUG: example

  # The URL of the vendor using EDD (example: https://searchwp.com)
  VENDOR_URL: https://example.com

  # The item ID of the download, this is different for every plugin and vendor, for example SearchWP's item ID is `216029`
  ITEM_ID: 1

  # A valid URL that your purchase is registered to in EDD
  ACTIVATION_URL: ${{github.server_url}}/${{github.repository}}
=======
  PACKAGE_SLUG: events-calendar-pro
>>>>>>> Stashed changes:.github/workflows/examples/facetwp.yml

jobs:
  update-plugin:
    name: Fetch and check versions
    runs-on: ubuntu-latest

    steps:

      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

<<<<<<< Updated upstream:.github/workflows/examples/edd.yml
      # Use EDD API to find download link for latest version, using the EDD item ID (different for every plugin)
      - name: Get download link from EDD
        id: EDDResponse
=======
     # Use FacetWP API to find download link for latest
      - name: Get download link from FacetWP API
        id: FacetWPAPIResponse
>>>>>>> Stashed changes:.github/workflows/examples/facetwp.yml
        uses: fjogeleit/http-request-action@master
        with:
          url: '${{ env.VENDOR_URL }}/?edd_action=get_version&item_id=${{ env.PACKAGE_SLUG }}&license=${{secrets.LICENSE_KEY}}&url=${{ env.ACTIVATION_URL }}'

<<<<<<< Updated upstream:.github/workflows/examples/edd.yml
      # Fetch latest version of SearchWP to download
=======
      # Fetch latest version
>>>>>>> Stashed changes:.github/workflows/examples/facetwp.yml
      - name: Fetch
        run: wget '${{fromJson(steps.EDDResponse.outputs.response).package}}' -O package.zip

      # Get the latest plugin and compare versions, commit if necessary
      - uses: ./.github/actions/update-plugin
        name: Update WordPress Plugin
        with:
          package-slug: ${{ env.PACKAGE_SLUG }}
          package-file-name: package.zip
