name: The Events Calendar Pro Updater

# Run this workflow twice daily
on:
  # schedule:
  #   - cron: '0 */12 * * *'
  workflow_dispatch:

env:
  PACKAGE_SLUG: events-calendar-pro

jobs:
  update-plugin:
    name: Fetch and check versions
    runs-on: ubuntu-latest

    steps:

      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Fetch latest version
      - name: Fetch
        run: wget 'https://pue.tri.be/api/plugins/v2/download?plugin=${{ env.PACKAGE_SLUG }}&key=${{secrets.TEC_KEY}}' -O package.zip

      # Get the latest plugin and compare versions, commit if necessary
      - uses: ./.github/actions/update-plugin
        name: Update WordPress Plugin
        with:
          package-slug: ${{ env.PACKAGE_SLUG }}
          package-file-name: package.zip
